name: 前端自动部署
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install
        run: |
          cd frontend
          npm install -g yarn
          yarn install
          yarn build
          cd ..
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./frontend/docker_build/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web3-vue:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web3-vue:${{  github.ref_name }}
      - name: describe
        run: |
          echo "docker verstion: ${{ secrets.DOCKERHUB_USERNAME }}/live-streaming-vue:$GITHUB_REF_NAME"
          echo "docker verstion: ${{ secrets.DOCKERHUB_USERNAME }}/live-streaming-vue:${{  github.ref_name }}"
